---
- name: Set up nzyme-tap on Ubuntu
  block:
    - name: Install nzyme-tap package (Ubuntu)
      apt:
        deb: "https://github.com/nzymedefense/nzyme/releases/download/2.0.0-alpha.6/nzyme-tap_2.0.0-alpha.6_ubuntu2204_amd64.deb"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Generate wifi configuration
      command: sudo nzyme-tap -g
      register: wifi_config

    - name: Configure nzyme-tap.conf (Ubuntu)
      template:
        src: nzyme-tap.conf.j2
        dest: /etc/nzyme/nzyme-tap.conf
      when: ansible_facts['os_family'] == 'Debian'
              
    - name: Set wifi configuration fact
      set_fact:
        wifi_config_block: "{{ wifi_config.stdout_lines | join('\n') }}"

    - name: Configure nzyme-tap.conf with wifi configuration
      blockinfile:
        path: /etc/nzyme/nzyme-tap.conf
        block: |
          {{ wifi_config_block }}
        marker: "# {mark} WiFi configuration"
        insertafter: 'accept_insecure_certs = true'

    - name: Start the tap (Ubuntu)
      systemd:
        name: nzyme-tap
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == 'Debian'

  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Set up nzyme-tap on Raspberry Pi OS
  block:
    - name: Install nzyme-tap package (Raspberry Pi)
      apt:
        deb: "https://github.com/nzymedefense/nzyme/releases/download/2.0.0-alpha.6/nzyme-tap_2.0.0-alpha.6_rpios11_arm64.deb"
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: Generate wifi configuration
      command: sudo nzyme-tap -g
      register: wifi_config

    - name: Configure nzyme-tap.conf (Raspberry Pi)
      template:
        src: nzyme-tap.conf.j2
        dest: /etc/nzyme/nzyme-tap.conf
      when: ansible_facts['os_family'] == 'Debian'

    - name: Set wifi configuration fact
      set_fact:
        wifi_config_block: "{{ wifi_config.stdout_lines | join('\n') }}"

    - name: Configure nzyme-tap.conf with wifi configuration
      blockinfile:
        path: /etc/nzyme/nzyme-tap.conf
        block: |
          {{ wifi_config_block }}
        marker: "# {mark} WiFi configuration"
        insertafter: 'accept_insecure_certs = true'

    - name: Start the tap (Raspberry Pi)
      systemd:
        name: nzyme-tap
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == 'Debian'

  when: ansible_facts['distribution'] == 'Debian'
