---
- name: Update apt and install dependencies
  apt:
    update_cache: yes
    name:
      - openjdk-11-jre-headless
      - postgresql-14
    state: present

- name: Download nzyme-node Debian package
  get_url:
    url: https://github.com/nzymedefense/nzyme/releases/download/2.0.0-alpha.5/nzyme-node_2.0.0-alpha.5.deb
    dest: "/tmp/nzyme-node_2.0.0-alpha.5.deb"

- name: Install nzyme-node Debian package
  apt:
    deb: "/tmp/nzyme-node_2.0.0-alpha.5.deb"
  
- name: Run the setup script
  script: setup_postgres.sh

- name: Configure nzyme.conf
  block:
    - name: Ensure nzyme configuration directory exists
      file:
        path: /etc/nzyme
        state: directory

    - name: Copy nzyme.conf file
      template:
        src: nzyme.conf.j2
        dest: /etc/nzyme/nzyme.conf

- name: Adjust Java options
  lineinfile:
    path: /etc/default/nzyme
    line: 'NZYME_JAVA_OPTS="-Xms2g -Xmx2g -XX:-OmitStackTraceInFastThrow"'

- name: Start nzyme service
  service:
    name: nzyme
    state: restarted
    enabled: yes
